import { describe, it, expect, vi, beforeEach } from 'vitest';

vi.mock('../../src/lib/firestore.js', async () => {
  const { createFakeFirestore } = await import('../helpers/fakeFirestore.js');
  const fake = createFakeFirestore();
  return { firestore: fake.firestore, FieldValue: fake.FieldValue, Timestamp: {} };
});

const { Session } = await import('@shopify/shopify-api');
const { shopify } = await import('../../src/config/shopify.js');
const { firestore } = await import('../../src/lib/firestore.js');
const { jobsRepo } = await import('../../src/models/jobsRepo.js');
const { publishJobToShopify, createProductForJob, PublishError, ProductCreateError } = await import(
  '../../src/services/publish.js'
);

const SHOP = 'publish-test-shop.myshopify.com';

function fakeSession() {
  return new Session({
    id: `offline_${SHOP}`,
    shop: SHOP,
    state: 'test',
    isOnline: false,
    accessToken: 'shpat_totally_real',
    expires: new Date(Date.now() + 60 * 60 * 1000),
  });
}

beforeEach(() => {
  vi.restoreAllMocks();
});

describe('publishJobToShopify', () => {
  it('publishes only the approved variations, marks the job published, and flags them publishedToShopify', async () => {
    await jobsRepo.create('job-publish-1', {
      shopDomain: SHOP,
      status: 'succeeded',
      contentType: 'scene',
      variations: [
        { url: 'https://cdn/1.png', approved: false, publishedToShopify: false },
        { url: 'https://cdn/2.png', approved: true, publishedToShopify: false },
      ],
    });
    const requestSpy = vi.spyOn(shopify.api.clients.Graphql.prototype, 'request').mockResolvedValue({
      data: { productCreateMedia: { media: [{ alt: 'Generated by MotionArt' }], mediaUserErrors: [] } },
      headers: {},
    });

    const result = await publishJobToShopify({
      session: fakeSession(),
      jobId: 'job-publish-1',
      productId: 'gid://shopify/Product/1',
      approvedIndices: [1],
    });

    expect(result.alreadyPublished).toBe(false);
    expect(requestSpy).toHaveBeenCalledWith(
      expect.any(String),
      expect.objectContaining({
        variables: expect.objectContaining({
          media: [expect.objectContaining({ originalSource: 'https://cdn/2.png', mediaContentType: 'IMAGE' })],
        }),
      }),
    );

    const stored = await jobsRepo.getById('job-publish-1');
    expect(stored.publishedAt).toBeTruthy();
    expect(stored.variations[0].publishedToShopify).toBe(false); // never approved, never published
    expect(stored.variations[1].publishedToShopify).toBe(true);
  });

  it('sends VIDEO as the media content type for a video job', async () => {
    await jobsRepo.create('job-publish-video', {
      shopDomain: SHOP,
      status: 'succeeded',
      contentType: 'video',
      variations: [{ url: 'https://cdn/clip.mp4', approved: true, publishedToShopify: false }],
    });
    const requestSpy = vi.spyOn(shopify.api.clients.Graphql.prototype, 'request').mockResolvedValue({
      data: { productCreateMedia: { media: [], mediaUserErrors: [] } },
      headers: {},
    });

    await publishJobToShopify({
      session: fakeSession(),
      jobId: 'job-publish-video',
      productId: 'gid://shopify/Product/1',
      approvedIndices: [0],
    });

    expect(requestSpy).toHaveBeenCalledWith(
      expect.any(String),
      expect.objectContaining({ variables: expect.objectContaining({ media: [expect.objectContaining({ mediaContentType: 'VIDEO' })] }) }),
    );
  });

  it('is idempotent — republishing an already-published job makes no Shopify API call at all', async () => {
    await jobsRepo.create('job-publish-again', {
      shopDomain: SHOP,
      status: 'succeeded',
      contentType: 'scene',
      publishedAt: new Date(),
      variations: [{ url: 'https://cdn/1.png', approved: true, publishedToShopify: true }],
    });
    const requestSpy = vi.spyOn(shopify.api.clients.Graphql.prototype, 'request');

    const result = await publishJobToShopify({
      session: fakeSession(),
      jobId: 'job-publish-again',
      productId: 'gid://shopify/Product/1',
      approvedIndices: [0],
    });

    expect(result.alreadyPublished).toBe(true);
    expect(requestSpy).not.toHaveBeenCalled();
  });

  it('throws PublishError and never claims the job when no variation was approved', async () => {
    await jobsRepo.create('job-publish-none-approved', {
      shopDomain: SHOP,
      status: 'succeeded',
      contentType: 'scene',
      variations: [{ url: 'https://cdn/1.png', approved: false, publishedToShopify: false }],
    });
    const requestSpy = vi.spyOn(shopify.api.clients.Graphql.prototype, 'request');

    await expect(
      publishJobToShopify({ session: fakeSession(), jobId: 'job-publish-none-approved', productId: 'gid://shopify/Product/1', approvedIndices: [] }),
    ).rejects.toBeInstanceOf(PublishError);
    expect(requestSpy).not.toHaveBeenCalled();

    // The claim must be released, not left stuck — a merchant approving a variation afterward and
    // retrying must be able to publish, not be permanently locked out by the failed first attempt.
    const stored = await jobsRepo.getById('job-publish-none-approved');
    expect(stored.publishedAt).toBeNull();
  });

  it('releases the publish claim and rethrows when Shopify returns mediaUserErrors', async () => {
    await jobsRepo.create('job-publish-shopify-error', {
      shopDomain: SHOP,
      status: 'succeeded',
      contentType: 'scene',
      variations: [{ url: 'https://cdn/1.png', approved: true, publishedToShopify: false }],
    });
    vi.spyOn(shopify.api.clients.Graphql.prototype, 'request').mockResolvedValue({
      data: { productCreateMedia: { media: [], mediaUserErrors: [{ field: ['media'], message: 'Invalid media URL' }] } },
      headers: {},
    });

    await expect(
      publishJobToShopify({ session: fakeSession(), jobId: 'job-publish-shopify-error', productId: 'gid://shopify/Product/1', approvedIndices: [0] }),
    ).rejects.toBeInstanceOf(PublishError);

    const stored = await jobsRepo.getById('job-publish-shopify-error');
    expect(stored.publishedAt).toBeNull(); // claim released — a retry is not locked out
  });
});

describe('createProductForJob', () => {
  it('creates a bare product and backfills productId onto the job', async () => {
    await jobsRepo.create('job-create-product', { shopDomain: SHOP, status: 'succeeded', variations: [] });
    vi.spyOn(shopify.api.clients.Graphql.prototype, 'request').mockResolvedValue({
      data: { productCreate: { product: { id: 'gid://shopify/Product/999', title: 'My new product' }, userErrors: [] } },
      headers: {},
    });

    const result = await createProductForJob({ session: fakeSession(), jobId: 'job-create-product', title: 'My new product' });

    expect(result).toEqual({ created: true, productId: 'gid://shopify/Product/999', productTitle: 'My new product' });
    const stored = await jobsRepo.getById('job-create-product');
    expect(stored.productId).toBe('gid://shopify/Product/999');
  });

  it('is idempotent — a job that already has a productId returns it instead of creating a second product', async () => {
    await jobsRepo.create('job-create-product-existing', {
      shopDomain: SHOP,
      status: 'succeeded',
      variations: [],
      productId: 'gid://shopify/Product/111',
    });
    const requestSpy = vi.spyOn(shopify.api.clients.Graphql.prototype, 'request');

    const result = await createProductForJob({ session: fakeSession(), jobId: 'job-create-product-existing', title: 'Ignored' });

    expect(result).toEqual({ created: false, productId: 'gid://shopify/Product/111' });
    expect(requestSpy).not.toHaveBeenCalled();
  });

  it('throws ProductCreateError and never sets productId when Shopify returns userErrors', async () => {
    await jobsRepo.create('job-create-product-fails', { shopDomain: SHOP, status: 'succeeded', variations: [] });
    vi.spyOn(shopify.api.clients.Graphql.prototype, 'request').mockResolvedValue({
      data: { productCreate: { product: null, userErrors: [{ field: ['title'], message: 'Title cannot be blank' }] } },
      headers: {},
    });

    await expect(createProductForJob({ session: fakeSession(), jobId: 'job-create-product-fails', title: '' })).rejects.toBeInstanceOf(
      ProductCreateError,
    );

    const stored = await jobsRepo.getById('job-create-product-fails');
    expect(stored.productId).toBeUndefined();
  });
});
