import { shopify } from '../config/shopify.js';
import { claimPublish, releasePublishClaim } from './idempotency.js';
import { jobsRepo } from '../models/jobsRepo.js';

export class PublishError extends Error {
  constructor(message) {
    super(message);
    this.name = 'PublishError';
    this.statusCode = 422;
  }
}

const PRODUCT_CREATE_MEDIA_MUTATION = `#graphql
  mutation productCreateMedia($productId: ID!, $media: [CreateMediaInput!]!) {
    productCreateMedia(productId: $productId, media: $media) {
      media { alt mediaContentType status }
      mediaUserErrors { field message }
      product { id title }
    }
  }
`;

// Publishes a job's approved variations to the product's Shopify media gallery. claimPublish()
// atomically guarantees a job can only ever be published once; if the Shopify call itself fails,
// the claim is released so a subsequent retry isn't permanently locked out (spec Section 13/17:
// generation pipelines must be idempotent — a retry must never double-publish).
export async function publishJobToShopify({ session, jobId, productId, approvedIndices = [] }) {
  const { alreadyPublished, job } = await claimPublish(jobId, approvedIndices);
  if (alreadyPublished) {
    return { alreadyPublished: true, job };
  }

  const approvedVariations = job.variations.filter((variation) => variation.approved);
  if (approvedVariations.length === 0) {
    await releasePublishClaim(jobId);
    throw new PublishError('No approved variations to publish');
  }

  try {
    const client = new shopify.api.clients.Graphql({ session });
    const media = approvedVariations.map((variation) => ({
      originalSource: variation.url,
      mediaContentType: job.contentType === 'video' ? 'VIDEO' : 'IMAGE',
      alt: 'Generated by VisualKit',
    }));

    const response = await client.request(PRODUCT_CREATE_MEDIA_MUTATION, {
      variables: { productId, media },
    });

    const userErrors = response.data?.productCreateMedia?.mediaUserErrors ?? [];
    if (userErrors.length > 0) {
      throw new PublishError(userErrors.map((error) => error.message).join('; '));
    }

    const updatedVariations = job.variations.map((variation) =>
      variation.approved ? { ...variation, publishedToShopify: true } : variation,
    );
    await jobsRepo.markPublished(jobId, updatedVariations);

    return { alreadyPublished: false, media: response.data.productCreateMedia.media };
  } catch (error) {
    await releasePublishClaim(jobId);
    throw error;
  }
}
